import { randomUUID } from "node:crypto";
import { resolve } from "node:path";
import { z } from "zod";

import type { AgentEngine, AgentTurnRequest } from "../agent/contracts.js";
import type { DshRuntime, DshTrust } from "../dsh/runner.js";
import { workerWorkspaceWrite } from "../dsh/runner-policy.js";
import { selectDshComposition } from "../dsh/select-composition.js";
import { DshConfigurationError, DshTimeoutError } from "../dsh/errors.js";
import type { DshOutput } from "../dsh/schema.js";
import type { TaskOutputSchema } from "../dsh/task-output.js";
import { githubToolInputSchemas } from "../tools/github-catalog.js";
import { githubToolSchema } from "../tools/schema.js";
import type { ExtensionPlan, AnyExtensionAudit } from "../extensions/plan.js";
import { nativeRuntimeToolNames } from "../extensions/profile.js";
import { PolicyDeniedError } from "../errors.js";
import { throwIfCancelled } from "../lifecycle/cancellation.js";
import { settleWithin } from "../lifecycle/deadline.js";
import type { PreparedWorkspace } from "../orchestration/workspace.js";
import { partitionDshToolPlanes, type DshTurnMetadata } from "../review/run.js";
import { assertNoSecretOutput } from "../security/env.js";
import { invokeRuntimeTask, type RuntimeClientConfig } from "./client.js";
import {
  canonicalRuntimeJson,
  MAX_RUNTIME_TASK_MS,
  runtimeBindingSchema,
  runtimeGrantsDigest,
  runtimeTaskDigest,
  runtimeTaskReplySchema,
  runtimeTaskSchema,
  validateRuntimeTaskOutput,
  type RuntimeBinding,
  type RuntimeTask,
  type RuntimeTaskReply,
} from "./runtime-task-protocol.js";
import { exportControllerSession, stageControllerSessionReply } from "./session-transfer.js";
import {
  applyWorkspaceDelta,
  createWorkspaceTransferManifest,
  packWorkspaceSnapshot,
  validateWorkspaceTransferDelta,
} from "./workspace-transfer.js";

export type FullEngineBinding = Pick<
  RuntimeBinding,
  "repository" | "baseSha" | "headSha" | "entity" | "ref"
>;
export interface FullEngineOptions {
  readonly workspace: PreparedWorkspace;
  readonly runtime: DshRuntime;
  readonly mode: "controlled" | "native";
  readonly operationIdentity: string;
  readonly extensionPlan?: ExtensionPlan;
  readonly taskOutputSchema?: TaskOutputSchema;
  readonly validationCommands?: readonly (readonly string[])[];
  /** Explicit offline fixtures only; production entrypoint never supplies this option. */
  readonly allowInsecureRuntimeTestOnly?: boolean;
  /** Test transport seam only. Production uses the authenticated bounded HTTP client. */
  readonly invoke?: (task: RuntimeTask, signal?: AbortSignal) => Promise<RuntimeTaskReply>;
  readonly fetchImplementation?: typeof fetch;
  readonly onTask?: (task: RuntimeTask) => void | Promise<void>;
  readonly onValidated?: (reply: RuntimeTaskReply) => void | Promise<void>;
  readonly onRequestId?: (id: string) => void;
}

const contextSchema = z.object({
  taskContext: z.object({
    repository: z.string(),
    entity: z
      .object({
        kind: z.enum(["pull_request", "issue"]),
        number: z.number().int().positive(),
        headSha: z.string().optional(),
        baseSha: z.string().optional(),
      })
      .optional(),
  }),
});
const receiptSchema = z.strictObject({
  schemaVersion: z.literal(1),
  callId: z.string().min(1).max(256),
  id: z.string().min(1).max(256),
  runtimeName: z.string().regex(/^[A-Za-z0-9_-]{1,128}$/u),
  provider: z.enum(["builtin", "mcp", "plugin", "denied"]),
  counted: z.boolean(),
  ok: z.boolean(),
  completed: z.boolean(),
  durationMs: z.number().int().nonnegative(),
  code: z.string().max(128).optional(),
});

/** Adapts cloud DSH into the original Controller loop; it neither tests nor publishes. */
export class AgentArtsFullEngine implements AgentEngine<DshOutput, DshTurnMetadata> {
  public readonly id = "dsh-agentarts";
  public readonly version = "0.2.0-rc.2";
  private revision = 0;
  private active = false;
  private unusable = false;
  private fixedRequest: string | undefined;
  private readonly binding: FullEngineBinding;

  public constructor(
    private readonly config: RuntimeClientConfig,
    private readonly trust: DshTrust,
    binding: FullEngineBinding,
    private readonly secrets: readonly string[],
    private readonly options: FullEngineOptions,
  ) {
    // The per-invocation fields are generated by the Controller, never task data.
    const checked = runtimeBindingSchema.parse({
      ...binding,
      taskId: randomUUID(),
      operation: "task",
      operationIdentity: options.operationIdentity,
      revision: 0,
      grantDigest: "0".repeat(64),
    });
    this.binding = {
      repository: checked.repository,
      baseSha: checked.baseSha,
      headSha: checked.headSha,
      entity: checked.entity,
      ref: checked.ref,
    };
  }

  public async runTurn(request: AgentTurnRequest) {
    if (this.active || this.unusable)
      throw new DshConfigurationError(
        "Runtime engine refuses concurrent turns or reuse after a rejected result",
      );
    this.active = true;
    const enteredAt = Date.now();
    try {
      return await this.turn(request);
    } catch (error: unknown) {
      this.unusable = true;
      throwIfCancelled(request.signal);
      if (Date.now() >= Math.min(request.deadlineMs, enteredAt + request.timeoutMs))
        throw new DshTimeoutError(request.timeoutMs);
      if (error instanceof Error && error.name === "TimeoutError")
        throw new DshTimeoutError(request.timeoutMs);
      if (error instanceof z.ZodError)
        throw new DshConfigurationError(
          "Runtime task failed independent strict boundary validation",
        );
      throw error;
    } finally {
      this.active = false;
    }
  }

  private async turn(request: AgentTurnRequest) {
    throwIfCancelled(request.signal);
    const startedAt = Date.now();
    const timeoutMs = Math.min(
      request.timeoutMs,
      request.deadlineMs - startedAt,
      MAX_RUNTIME_TASK_MS,
    );
    if (!Number.isSafeInteger(timeoutMs) || timeoutMs <= 0)
      throw new DshTimeoutError(Math.max(0, timeoutMs));
    const deadlineMs = Math.min(request.deadlineMs, startedAt + timeoutMs);
    const signal = AbortSignal.any([
      AbortSignal.timeout(timeoutMs),
      ...(request.signal === undefined ? [] : [request.signal]),
    ]);
    const guard = () => {
      throwIfCancelled(request.signal);
      if (Date.now() >= deadlineMs) throw new DshTimeoutError(timeoutMs);
      throwIfCancelled(signal);
    };
    if (resolve(request.workspacePath) !== resolve(this.options.workspace.agentWorkspace))
      throw new PolicyDeniedError("Runtime turn changed the Controller's bound workspace");
    if (request.session !== undefined)
      throw new DshConfigurationError(
        "Use the original DSH checkpoint transport, not an opaque model session handle",
      );
    const write = request.requestedAccess === "write";
    if (write && (this.trust !== "trusted-write" || this.options.workspace.snapshot === undefined))
      throw new PolicyDeniedError(
        "Cloud workspace writes require the original trusted Controller snapshot",
      );
    const packet = contextSchema.parse(request.context).taskContext;
    if (packet.repository !== this.binding.repository)
      throw new PolicyDeniedError(
        "Runtime task repository does not match immutable Controller binding",
      );
    if (this.binding.entity.kind === "repository") {
      if (packet.entity !== undefined)
        throw new PolicyDeniedError("Repository task acquired an unbound entity");
    } else if (
      packet.entity?.kind !== this.binding.entity.kind ||
      packet.entity.number !== this.binding.entity.number
    )
      throw new PolicyDeniedError(
        "Runtime task entity does not match immutable Controller binding",
      );
    else if (
      this.binding.entity.kind === "pull_request" &&
      (packet.entity.headSha !== this.binding.headSha ||
        packet.entity.baseSha !== this.binding.baseSha)
    )
      throw new PolicyDeniedError("Runtime task base/head no longer match the Controller binding");
    const { nativeTools, controllerTools, extensionTools } = partitionDshToolPlanes(request.tools);
    const plan = this.trust === "untrusted" ? undefined : this.options.extensionPlan;
    const workspaceWrite =
      write &&
      workerWorkspaceWrite(
        {
          operation: request.operation,
          prompt: "",
          trust: this.trust,
          isolation: "docker",
          timeoutMs,
          maxOutputBytes: 1,
          apiKey: "runtime-managed",
          baseUrl: "https://api.deepseek.com",
          webSearchBaseUrl: "https://api.deepseek.com/anthropic/v1",
          dshVersion: this.version,
          containerImage: "runtime-managed",
          nativeTools,
          ...(plan === undefined ? {} : { extensions: plan }),
        },
        selectDshComposition(this.options.mode).create(),
      );
    if (plan?.profileName === "github-action") {
      if (
        canonicalRuntimeJson(extensionTools.map(({ id }) => id).sort()) !==
        canonicalRuntimeJson(plan.manifests.map(({ id }) => id).sort())
      )
        throw new PolicyDeniedError(
          "Runtime extension grants differ from the original Controller plan",
        );
    } else if (extensionTools.length > 0)
      throw new PolicyDeniedError("Unbound extension tool manifests are forbidden");
    const grants = {
      mode: this.options.mode,
      trust: this.trust,
      requestedAccess: request.requestedAccess,
      tools: [...nativeTools],
      toolCatalog: controllerTools,
      ...(plan === undefined ? {} : { extensions: plan }),
    };
    const fixed = canonicalRuntimeJson({
      operation: request.operation,
      requestedAccess: request.requestedAccess,
      instructions: request.instructions,
      grants,
      binding: this.binding,
    });
    if (this.fixedRequest !== undefined && this.fixedRequest !== fixed)
      throw new PolicyDeniedError("Runtime authority changed between repair turns");
    this.fixedRequest = fixed;
    const taskId = randomUUID();
    const binding = runtimeBindingSchema.parse({
      ...this.binding,
      taskId,
      operation: request.operation,
      operationIdentity: this.options.operationIdentity,
      revision: this.revision,
      grantDigest: runtimeGrantsDigest(grants),
    });
    const transferOptions = {
      knownSecrets: [...this.secrets, this.config.apiKey],
      signal,
      deadlineMs,
    };
    const workspace =
      this.trust === "untrusted"
        ? createWorkspaceTransferManifest(binding, [], transferOptions)
        : await packWorkspaceSnapshot(
            this.options.workspace.snapshot ?? {
              sourceRoot: request.workspacePath,
              workerRoot: request.workspacePath,
              baseline: new Map(),
            },
            binding,
            transferOptions,
          );
    guard();
    const session = await exportControllerSession(
      this.options.runtime,
      workspaceWrite,
      transferOptions.knownSecrets,
    );
    guard();
    const task = runtimeTaskSchema.parse({
      schemaVersion: 3,
      taskId,
      operation: request.operation,
      binding,
      ...grants,
      timeoutMs: Math.max(1, deadlineMs - Date.now()),
      instructions: request.instructions,
      context: JSON.parse(JSON.stringify(request.context)) as unknown,
      workspace,
      ...(session === undefined ? {} : { session }),
      ...(request.operation !== "task" || this.options.taskOutputSchema === undefined
        ? {}
        : { taskOutputSchema: this.options.taskOutputSchema }),
    });
    assertNoSecretOutput("prompt", JSON.stringify(task), transferOptions.knownSecrets);
    await this.options.onTask?.(task);
    guard();
    const invocation =
      this.options.invoke === undefined
        ? invokeRuntimeTask(this.config, task, {
            signal,
            ...(this.options.fetchImplementation === undefined
              ? {}
              : { fetchImplementation: this.options.fetchImplementation }),
            ...(this.options.onRequestId === undefined
              ? {}
              : { onRequestId: this.options.onRequestId }),
          })
        : this.options.invoke(task, signal);
    // Race only the remote computation. No Controller filesystem work is detached.
    const pending = await settleWithin(invocation, Math.max(1, deadlineMs - Date.now()), signal);
    guard();
    if (!pending.settled) throw new DshTimeoutError(timeoutMs);
    const reply = runtimeTaskReplySchema.parse(
      JSON.parse(JSON.stringify(pending.value)) as unknown,
    );
    assertNoSecretOutput("stdout", JSON.stringify(reply), transferOptions.knownSecrets);
    if (
      reply.taskId !== task.taskId ||
      reply.operation !== task.operation ||
      canonicalRuntimeJson(reply.binding) !== canonicalRuntimeJson(task.binding) ||
      reply.taskDigest !== runtimeTaskDigest(task) ||
      reply.workspaceDigest !== task.workspace.digest
    )
      throw new DshConfigurationError(
        "Runtime task, operation, grants, commits or input workspace binding mismatch",
      );
    const output = validateRuntimeTaskOutput(reply.output, task);
    const sandbox = reply.sandboxEvidence;
    if (
      sandbox.workspaceAccess !== (workspaceWrite ? "read-write" : "read-only") ||
      (this.options.allowInsecureRuntimeTestOnly !== true &&
        (sandbox.backend !== "agentarts-bwrap" ||
          !sandbox.processIsolated ||
          !sandbox.networkIsolated))
    )
      throw new DshConfigurationError(
        "Runtime did not preserve the required isolated workspace boundary",
      );
    let extensionAudit: AnyExtensionAudit | undefined;
    if (reply.extensionAudit !== undefined) {
      if (plan === undefined)
        throw new DshConfigurationError("Runtime acquired an unbound extension audit");
      const actual = z.record(z.string(), z.json()).parse(reply.extensionAudit);
      const expected = { ...plan.audit };
      const { runtimeLock, ...base } = actual;
      delete expected.runtimeLock;
      if (canonicalRuntimeJson(base) !== canonicalRuntimeJson(expected))
        throw new DshConfigurationError("Runtime extension audit changed the admitted plan");
      if (runtimeLock !== undefined)
        z.strictObject({
          schemaVersion: z.literal(1),
          algorithm: z.literal("sha256"),
          digest: z.string().regex(/^[a-f0-9]{64}$/u),
          lockfileVersion: z.literal(3),
          packageCount: z.number().int().nonnegative(),
          extensionPackageCount: z.number().int().nonnegative(),
        }).parse(runtimeLock);
      extensionAudit = actual as unknown as AnyExtensionAudit;
    } else if (
      plan !== undefined &&
      (plan.profileName === "github-action" || plan.audit.entries.length > 0)
    )
      throw new DshConfigurationError("Runtime omitted its admitted extension audit");
    if (output.toolRequest?.id.startsWith("github.")) {
      const id = githubToolSchema.parse(output.toolRequest.id);
      githubToolInputSchemas[id].parse(output.toolRequest.input ?? {});
    }
    const receipts = reply.toolReceipts.map((value) => {
      const { code, ...rest } = receiptSchema.parse(value);
      return { ...rest, ...(code === undefined ? {} : { code }) };
    });
    const receiptIds = new Set<string>();
    for (const receipt of receipts) {
      if (receiptIds.has(receipt.callId))
        throw new DshConfigurationError("Runtime repeated a native tool receipt identity");
      receiptIds.add(receipt.callId);
      if (receipt.counted && !receipt.completed)
        throw new DshConfigurationError("Runtime returned an unfinished tool invocation");
      if (receipt.provider === "denied") {
        if (receipt.counted || receipt.ok)
          throw new DshConfigurationError("Denied Runtime tool cannot report execution success");
      } else {
        const granted =
          receipt.provider === "builtin"
            ? task.tools.includes(receipt.id as (typeof task.tools)[number]) &&
              nativeRuntimeToolNames([receipt.id as (typeof task.tools)[number]]).includes(
                receipt.runtimeName,
              )
            : plan?.profileName === "github-action" &&
              plan.tools.some(
                (tool) =>
                  tool.id === receipt.id &&
                  tool.runtimeName === receipt.runtimeName &&
                  tool.provider === receipt.provider,
              );
        if (!granted) throw new PolicyDeniedError("Runtime reported an ungranted tool invocation");
      }
    }
    if (this.trust === "untrusted" && receipts.length > 0)
      throw new PolicyDeniedError("Untrusted Runtime cannot invoke repository tools");
    if (write ? reply.delta === null : reply.delta !== null)
      throw new DshConfigurationError("Runtime returned the wrong read/write workspace result");
    if (!workspaceWrite && reply.delta !== null && reply.delta.changes.length > 0)
      throw new PolicyDeniedError(
        "Runtime changed files without an effective workspace write grant",
      );
    if (reply.delta !== null)
      validateWorkspaceTransferDelta(task.workspace, reply.delta, transferOptions);
    if ((session === undefined) !== (reply.session === undefined))
      throw new DshConfigurationError(
        "Runtime changed whether the original Session transport is enabled",
      );
    const staged =
      session === undefined
        ? undefined
        : await stageControllerSessionReply(
            this.options.runtime,
            session,
            reply.session,
            workspaceWrite,
            {
              additionalSecrets: transferOptions.knownSecrets,
              signal,
              deadlineMs,
            },
          );
    try {
      guard();
      if (reply.delta !== null) {
        const snapshot = this.options.workspace.snapshot;
        if (snapshot === undefined)
          throw new PolicyDeniedError("Runtime has no Controller snapshot for delta installation");
        await applyWorkspaceDelta(snapshot, task.workspace, reply.delta, {
          ...transferOptions,
          ...(this.options.validationCommands === undefined
            ? {}
            : { validationCommands: this.options.validationCommands }),
        });
      }
      guard();
      await staged?.commit();
      guard();
      this.revision += 1;
      await this.options.onValidated?.(reply);
      guard();
      return {
        output,
        durationMs: reply.durationMs,
        metadata: {
          toolReceipts: receipts,
          ...(reply.observedTools === undefined ? {} : { observedTools: reply.observedTools }),
          ...(extensionAudit === undefined ? {} : { extensionAudit }),
          isolationReport: {
            backend: "agentarts" as const,
            credentialMediated: true as const,
            repoToolsEnabled: task.tools.length > 0,
            processIsolated: sandbox.processIsolated,
            networkIsolated: sandbox.networkIsolated,
            workspaceAccess: sandbox.workspaceAccess,
            extensionProfile: plan?.profileName ?? ("none" as const),
            limitations: [
              "AgentArts deployment and tenant limits require separate cloud verification.",
              "Native DSH mode owns its internal capability inventory; observed names are telemetry, not Controller tool grants.",
              "Returned file bytes are staged and checked against the original snapshot; the original Controller validates tests and owns GitHub publication.",
            ],
          },
        },
      };
    } finally {
      await staged?.dispose();
    }
  }
}
