#!/usr/bin/env node
/** Embed the original installer; no cloud calls, credentials or repository script discovery. */
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { resolve, join } from "node:path";
import { fileURLToPath, URL } from "node:url";
import { runInstaller } from "../packages/create-deepseek-harness-action/src/installer.mjs";

const root = fileURLToPath(new URL("../", import.meta.url));
const usage = [
  "Usage: node agentarts/install.mjs --action-ref <40-character published commit SHA>",
  "  --mode review|commands|both [--dsh-mode controlled|native]",
  "  [--test-commands '<JSON argv arrays>'] [--container-image '<name>@sha256:<digest>']",
  "Creates inherited workflow choices using the AgentArts Action; never overwrites existing files.",
  "Runtime variables and the Controller inbound Secret must be configured separately.",
].join("\n");
function cloudArguments(argv) {
  let actionRef;
  const remaining = [];
  for (let index = 0; index < argv.length; index++) {
    const value = argv[index];
    if (value === "--action-ref" || value?.startsWith("--action-ref=")) {
      if (actionRef !== undefined) throw new Error("--action-ref may be provided only once");
      actionRef = value === "--action-ref" ? argv[++index] : value.slice("--action-ref=".length);
      if (typeof actionRef !== "string" || !/^[a-f0-9]{40}$/u.test(actionRef))
        throw new Error("--action-ref requires one immutable 40-character lowercase commit SHA");
    } else remaining.push(value);
  }
  if (remaining.includes("--help") || remaining.includes("-h"))
    return { help: true, remaining, actionRef };
  if (actionRef === undefined)
    throw new Error("Choose the published Action commit explicitly with --action-ref");
  return { help: false, remaining, actionRef };
}
function transform(contents, actionRef) {
  let converted = contents.replace(
    /^([ \t]*)- uses: Lixiaoyiao\/deepseek-harness-action@[a-f0-9]{40}\r?\n\1 {2}with:\r?\n/mu,
    (_old, indent) =>
      [
        indent + "- uses: Lixiaoyiao/Huawei-AgentArts-action/agentarts@" + actionRef,
        indent + "  with:",
        indent + "    runtime-origin: ${{ vars.AGENTARTS_RUNTIME_ORIGIN }}",
        indent + "    runtime-name: ${{ vars.AGENTARTS_RUNTIME_NAME }}",
        indent + "    runtime-endpoint: ${{ vars.AGENTARTS_RUNTIME_ENDPOINT }}",
        indent + "    runtime-api-key: ${{ secrets.AGENTARTS_RUNTIME_API_KEY }}",
        "",
      ].join("\n"),
  );
  converted = converted.replace(
    /^[ \t]*(?:deepseek-api-key|dsh-version|dsh-executable|isolation|base-url|web-search-base-url):[^\r\n]*(?:\r?\n|$)/gmu,
    "",
  );
  if (
    (
      converted.match(
        /uses: Lixiaoyiao\/Huawei-AgentArts-action\/agentarts@[a-f0-9]{40}(?:\s|$)/gu,
      ) ?? []
    ).length !== 1 ||
    converted.includes("DEEPSEEK_API_KEY") ||
    converted.includes("Lixiaoyiao/deepseek-harness-action@")
  )
    throw new Error("Inherited template could not be safely converted to the AgentArts entry");
  return converted.replace(
    "# Generated by create-deepseek-harness-action.",
    "# Generated by AgentArts installer from the inherited DSH workflow template.",
  );
}

export async function runAgentArtsInstaller(options = {}) {
  const parsed = cloudArguments(options.argv ?? process.argv.slice(2));
  const output = options.output ?? process.stdout;
  if (parsed.help) {
    output.write(usage + "\n");
    return { dshMode: "controlled", createdFiles: [] };
  }
  const lock = JSON.parse(await readFile(join(root, "agentarts/upstream-lock.json"), "utf8"));
  if (!/^[a-f0-9]{40}$/u.test(lock.upstreamCommit))
    throw new Error("Upstream baseline must be immutable");
  const stage = await mkdtemp(join(tmpdir(), "agentarts-installer-"));
  try {
    await mkdir(join(stage, "templates"));
    for (const kind of ["review", "commands"]) {
      const original = await readFile(
        join(root, "packages/create-deepseek-harness-action/src/templates", "dsh-" + kind + ".yml"),
        "utf8",
      );
      for (const mode of ["controlled", "native"]) {
        const qualified = original
          .replaceAll("__DSH_ACTION_RELEASE_SHA__", lock.upstreamCommit)
          .replace(/^([ \t]*)# __DSH_MODE_INPUT__[ \t]*\r?\n/mu, (_line, indent) =>
            mode === "native" ? indent + "dsh-mode: native\n" : "",
          );
        if (qualified.includes("__DSH_"))
          throw new Error("Inherited template contains unresolved binding markers");
        await writeFile(
          join(stage, "templates", "dsh-" + kind + (mode === "native" ? "-native" : "") + ".yml"),
          qualified,
          { flag: "wx", mode: 0o600 },
        );
      }
    }
    return await runInstaller({
      ...options,
      argv: parsed.remaining,
      templateDirectory: join(stage, "templates"),
      transformTemplate: (contents) => transform(contents, parsed.actionRef),
      printSuccess: (stream, mode, dshMode, files, commands) => {
        stream.write(
          "Created AgentArts workflow files:\n" +
            files.map((file) => "  " + file).join("\n") +
            "\n",
        );
        stream.write("DSH mode: " + dshMode + "\nAction commit: " + parsed.actionRef + "\n");
        stream.write(
          "Set repository vars AGENTARTS_RUNTIME_ORIGIN, AGENTARTS_RUNTIME_NAME and AGENTARTS_RUNTIME_ENDPOINT (fixed alias; not Latest).\n",
        );
        stream.write(
          "Set Controller Secret AGENTARTS_RUNTIME_API_KEY. The model key belongs only to the trusted Runtime supervisor.\n",
        );
        if (mode !== "review")
          stream.write(
            commands === undefined
              ? "Write workflows retain a fail-closed test placeholder; replace it with reviewed validation argv before use.\n"
              : "Review the explicitly supplied credential-free validation argv and digest-pinned test image before use.\n",
          );
        stream.write(
          "No repository scripts, cloud resources, model calls or credentials were inspected. Actual Runtime kernel isolation, network, alias and GitHub permissions remain execution checks.\n",
        );
        stream.write(
          "Documentation: https://github.com/Lixiaoyiao/Huawei-AgentArts-action/blob/" +
            parsed.actionRef +
            "/docs/agentarts/deployment.md\n",
        );
      },
    });
  } finally {
    await rm(stage, { recursive: true, force: true });
  }
}
if (process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url))
  void runAgentArtsInstaller().catch((error) => {
    process.stderr.write(
      (error instanceof Error ? error.message : "AgentArts installation failed") + "\n",
    );
    process.exitCode = 1;
  });
